img_size: [120,160]
top_cutoff: 50

# should be an array of 2 elements. The first is the name of the class
# and the second should be the parameters.
# The class should be an abstract instance of LineDetectorInterface
detector:
  - dt_project_lane_detector.LanePointDetector
  - configuration:
    # Default parameters
    #   dilation_kernel_size: 3
    #   canny_thresholds: [80,200]
    #   hough_threshold: 2
    #   hough_min_line_length: 3
    #   hough_max_line_gap:    1

      hsv_white1:  [0,0,150]
      hsv_white2:  [180,100,255]
      hsv_yellow1: [25,140,100]
      hsv_yellow2: [45,255,255]
      hsv_red1:    [0,140,100]
      hsv_red2:    [15,255,255]
      hsv_red3:    [165,140,100]
      hsv_red4:    [180,255,255]

      # DT PROJECT PARAMETERS
      # Smoothing filter parameters
      bilateral_pixel_neighbourhood: 7
      bilateral_sigma_color: 75
      bilateral_sigma_space: 75
     
      # Shi-Tomasi corner parameters
      max_corners: 50
      yellow_quality_level: 0.01
      yellow_min_distance: 5
      yellow_block_size: 7
      
      white_quality_level: 0.001
      white_min_distance: 10
      white_block_size: 15
      
      # TODO : Set these values
      red_quality_level: 0.001
      red_min_distance: 10
      red_block_size: 15

      # White line detection
      dilation_size: 3
      min_component_size: 100
      canny_thresholds: [80,200]
      hough_threshold: 2
      hough_min_line_length: 3
      hough_max_line_gap:    1
      

detector_intersection:
 - dt_project_lane_detector.LineDetectorHSV
 - configuration:
     dilation_kernel_size: 3
     canny_thresholds: [80,200]
     hough_threshold: 2
     hough_min_line_length: 3
     hough_max_line_gap:    1

     hsv_white1:  [0,0,150]
     hsv_white2:  [180,100,255]
     hsv_yellow1: [25,140,100]
     hsv_yellow2: [45,255,255]
     hsv_red1:    [0,50,100]
     hsv_red2:    [15,255,255]
     hsv_red3:    [165,50,100]
     hsv_red4:    [180,255,255]
